spring:
  datasource:
    url: jdbc:h2:mem:persons
#    username: root
#    password: root
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
#    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        generate_statistics: true
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

  h2.console.enabled: true
